# Generated by Django 4.1.5 on 2023-02-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='protocol',
            field=models.CharField(blank=True, max_length=47, null=True),
        ),
    ]
