# Generated by Django 4.1.5 on 2023-01-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_carro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='plca',
            new_name='placa',
        ),
    ]
